import type { Metadata } from 'next';
import { bodyFont } from './fonts/fonts';
import './ui/globals.css';

export const metadata: Metadata = {
   title: 'RPG Notes',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${bodyFont.className}`}>{children}</body>
      </html>
   );
}
